name: 'Axe Slack Reporter'
description: 'Report axe-core findings to Slack'
inputs:
  result:  # Result from axe
    description: 'json-result from axe-core'
    required: true
outputs:
  status: # Status of the action
    description: '0 if OK, non-zero if error'
runs:
  using: 'node12'
  main: 'dist/index.js --experimental-modules'